import type { LicenseDefinition } from "../../types/index.js";
import { official, osi, spdx, SOURCES } from "../sources/index.js";

const openSourceBase = {
  category: "OPEN_SOURCE",
  osiApproved: true,
  commercialUse: "PERMITTED",
  privateUse: "PERMITTED",
  modification: "PERMITTED",
  distribution: "PERMITTED",
  attributionRequired: true,
  licenseNoticeRequired: true,
  copyrightNoticeRequired: true,
  restrictions: [],
} as const;

export const MPL_2_0: LicenseDefinition = {
  ...openSourceBase,
  id: "MPL-2.0",
  name: "Mozilla Public License 2.0",
  spdxId: "MPL-2.0",
  family: "FILE_LEVEL_COPYLEFT",
  fsfGplCompatible: true,
  sublicensing: "CONDITIONAL",
  patentGrant: true,
  patentRetaliation: true,
  trademarkUse: "PROHIBITED",
  sourceDisclosure: "MODIFIED_FILES",
  copyleft: "FILE_LEVEL",
  networkCopyleft: false,
  sameLicenseRequired: true,
  stateChangesRequired: false,
  description:
    "A file-level copyleft licence. Files covered by MPL-2.0 (and modifications to them) must remain under MPL-2.0 and their source must be made available when distributed in executable form; they may be combined with files under other terms in a Larger Work (section 3.3).",
  permissions: [
    "Commercial use",
    "Modification",
    "Distribution",
    "Express patent licence",
    "Private use",
    "Combination in a Larger Work",
  ],
  conditions: [
    "Covered files and their modifications stay under MPL-2.0",
    "Make source code of covered files available when distributing executable form",
    "Retain copyright and licence notices",
  ],
  limitations: [
    "No warranty",
    "No liability",
    "No trademark rights",
    "Patent licence terminates on patent litigation (section 5.2)",
  ],
  sources: [
    spdx("MPL-2.0"),
    osi("mpl-2-0", "Mozilla Public License 2.0"),
    official("Mozilla Public License 2.0 (official text)", "https://www.mozilla.org/en-US/MPL/2.0/"),
    SOURCES.mplFaq,
  ],
};

export const LGPL_2_1: LicenseDefinition = {
  ...openSourceBase,
  id: "LGPL-2.1",
  name: "GNU Lesser General Public License v2.1",
  spdxId: "LGPL-2.1-only",
  family: "WEAK_COPYLEFT",
  fsfGplCompatible: true,
  sublicensing: "CONDITIONAL",
  patentGrant: false,
  patentRetaliation: false,
  trademarkUse: "UNKNOWN",
  sourceDisclosure: "LIBRARY_AND_MODIFICATIONS",
  copyleft: "WEAK",
  networkCopyleft: false,
  sameLicenseRequired: true,
  stateChangesRequired: true,
  description:
    "A weak copyleft licence for libraries. The library and modifications to it must stay under LGPL-2.1; a separate program that uses the library may be distributed under its own terms if the section 6 requirements (e.g. allowing relinking with a modified library) are met.",
  permissions: [
    "Commercial use",
    "Modification",
    "Distribution",
    "Private use",
    "Use by non-LGPL programs under section 6",
  ],
  conditions: [
    "Provide source of the library and of modifications to it when distributing",
    "Keep the library and its modifications under LGPL-2.1 (or convert to GPL under section 3)",
    "Allow the user to relink with a modified version of the library (section 6)",
    "Permit reverse engineering for debugging such modifications (section 6)",
    "Mark modified files with notices of changes",
  ],
  limitations: ["No warranty", "No liability", "No express patent licence"],
  sources: [
    spdx("LGPL-2.1-only"),
    osi("lgpl-2-1", "GNU Lesser General Public License version 2.1"),
    official("GNU LGPL v2.1 (official text)", "https://www.gnu.org/licenses/old-licenses/lgpl-2.1.html"),
    SOURCES.lgplFaqLinking,
  ],
};

export const LGPL_3_0: LicenseDefinition = {
  ...openSourceBase,
  id: "LGPL-3.0",
  name: "GNU Lesser General Public License v3.0",
  spdxId: "LGPL-3.0-only",
  family: "WEAK_COPYLEFT",
  fsfGplCompatible: true,
  sublicensing: "CONDITIONAL",
  patentGrant: true,
  patentRetaliation: true,
  trademarkUse: "UNKNOWN",
  sourceDisclosure: "LIBRARY_AND_MODIFICATIONS",
  copyleft: "WEAK",
  networkCopyleft: false,
  sameLicenseRequired: true,
  stateChangesRequired: true,
  description:
    "GPL-3.0 plus additional permissions. A Combined Work that uses the library may be distributed under terms of your choice if section 4 is met (notices, licence copies, and a way to relink or use a modified version of the library).",
  permissions: [
    "Commercial use",
    "Modification",
    "Distribution",
    "Private use",
    "Express patent licence",
    "Combined Works under section 4",
  ],
  conditions: [
    "Provide source of the library and of modifications to it when distributing",
    "Give prominent notice that the library is used and that it is covered by the LGPL",
    "Accompany the Combined Work with copies of the GPL and LGPL",
    "Provide a way to relink or use a shared library so users can run a modified library version (section 4(d))",
    "Provide Installation Information where required for User Products",
  ],
  limitations: [
    "No warranty",
    "No liability",
    "Patent licence terminates on patent litigation (GPL-3.0 section 10/11)",
  ],
  sources: [
    spdx("LGPL-3.0-only"),
    osi("lgpl-3-0", "GNU Lesser General Public License version 3"),
    official("GNU LGPL v3.0 (official text)", "https://www.gnu.org/licenses/lgpl-3.0.html"),
    SOURCES.lgplFaqLinking,
  ],
};

export const GPL_2_0: LicenseDefinition = {
  ...openSourceBase,
  id: "GPL-2.0",
  name: "GNU General Public License v2.0",
  spdxId: "GPL-2.0-only",
  family: "STRONG_COPYLEFT",
  fsfGplCompatible: false,
  sublicensing: "PROHIBITED",
  patentGrant: false,
  patentRetaliation: false,
  trademarkUse: "UNKNOWN",
  sourceDisclosure: "DERIVATIVE_WORK",
  copyleft: "STRONG",
  networkCopyleft: false,
  sameLicenseRequired: true,
  stateChangesRequired: true,
  description:
    "A strong copyleft licence. When a work based on the program is distributed, the whole work must be licensed under GPL-2.0 and complete corresponding source must be offered. Obligations are triggered by distribution, not by private use.",
  permissions: ["Commercial use", "Modification", "Distribution", "Private use"],
  conditions: [
    "Distribute the whole work based on the program under GPL-2.0",
    "Provide or offer complete corresponding source code",
    "Keep copyright and licence notices intact and include the licence",
    "Mark modified files with notices of changes and dates",
  ],
  limitations: ["No warranty", "No liability", "No additional restrictions may be imposed on recipients"],
  sources: [
    spdx("GPL-2.0-only"),
    osi("gpl-2-0", "GNU General Public License version 2"),
    official("GNU GPL v2.0 (official text)", "https://www.gnu.org/licenses/old-licenses/gpl-2.0.html"),
    SOURCES.gplFaq,
  ],
};

export const GPL_3_0: LicenseDefinition = {
  ...openSourceBase,
  id: "GPL-3.0",
  name: "GNU General Public License v3.0",
  spdxId: "GPL-3.0-only",
  family: "STRONG_COPYLEFT",
  fsfGplCompatible: true,
  sublicensing: "PROHIBITED",
  patentGrant: true,
  patentRetaliation: true,
  trademarkUse: "UNKNOWN",
  sourceDisclosure: "DERIVATIVE_WORK",
  copyleft: "STRONG",
  networkCopyleft: false,
  sameLicenseRequired: true,
  stateChangesRequired: true,
  description:
    "A strong copyleft licence. Conveying a work based on the program requires licensing the whole work under GPL-3.0 and providing Corresponding Source. Works that are run or modified but not conveyed carry no such conditions (section 2). Includes an express patent licence (section 11).",
  permissions: ["Commercial use", "Modification", "Distribution", "Private use", "Express patent licence"],
  conditions: [
    "License the whole conveyed work under GPL-3.0",
    "Provide Corresponding Source when conveying object code",
    "Keep copyright and licence notices and include the licence",
    "Mark modified versions with prominent notices of changes",
    "Provide Installation Information for User Products",
  ],
  limitations: [
    "No warranty",
    "No liability",
    "No further restrictions on recipients",
    "Patent licence terminates on patent litigation",
  ],
  sources: [
    spdx("GPL-3.0-only"),
    osi("gpl-3-0", "GNU General Public License version 3"),
    official("GNU GPL v3.0 (official text)", "https://www.gnu.org/licenses/gpl-3.0.html"),
    SOURCES.gplFaq,
  ],
};

export const AGPL_3_0: LicenseDefinition = {
  ...openSourceBase,
  id: "AGPL-3.0",
  name: "GNU Affero General Public License v3.0",
  spdxId: "AGPL-3.0-only",
  family: "NETWORK_COPYLEFT",
  fsfGplCompatible: true,
  sublicensing: "PROHIBITED",
  patentGrant: true,
  patentRetaliation: true,
  trademarkUse: "UNKNOWN",
  sourceDisclosure: "DERIVATIVE_WORK",
  copyleft: "NETWORK",
  networkCopyleft: true,
  sameLicenseRequired: true,
  stateChangesRequired: true,
  description:
    "GPL-3.0 terms plus section 13: if you modify the program, users interacting with it remotely over a network must be offered the Corresponding Source of your modified version.",
  permissions: ["Commercial use", "Modification", "Distribution", "Private use", "Express patent licence"],
  conditions: [
    "License the whole conveyed work under AGPL-3.0",
    "Provide Corresponding Source when conveying",
    "Offer Corresponding Source of a modified version to users interacting with it over a network (section 13)",
    "Keep copyright and licence notices and include the licence",
  ],
  limitations: ["No warranty", "No liability", "No further restrictions on recipients"],
  sources: [
    spdx("AGPL-3.0-only"),
    osi("agpl-v3", "GNU Affero General Public License version 3"),
    official("GNU AGPL v3.0 (official text)", "https://www.gnu.org/licenses/agpl-3.0.html"),
    SOURCES.gplFaq,
  ],
};

export const EPL_2_0: LicenseDefinition = {
  ...openSourceBase,
  id: "EPL-2.0",
  name: "Eclipse Public License 2.0",
  spdxId: "EPL-2.0",
  family: "WEAK_COPYLEFT",
  fsfGplCompatible: false,
  sublicensing: "CONDITIONAL",
  patentGrant: true,
  patentRetaliation: true,
  trademarkUse: "PROHIBITED",
  sourceDisclosure: "MODULE_AND_MODIFICATIONS",
  copyleft: "WEAK",
  networkCopyleft: false,
  sameLicenseRequired: true,
  stateChangesRequired: false,
  description:
    "A weak copyleft licence. Modifications to EPL-2.0 code (Modified Works) must be made available under EPL-2.0; separate modules that merely link or interface with it are not covered. A Secondary License (e.g. GPL-2.0) may apply only if the initial contributor designated one in Exhibit A.",
  permissions: ["Commercial use", "Modification", "Distribution", "Express patent licence", "Private use"],
  conditions: [
    "Make source of EPL-2.0 code and Modified Works available under EPL-2.0 when distributing",
    "Retain copyright notices and include the licence or a notice of it",
  ],
  limitations: [
    "No warranty",
    "No liability",
    "No trademark rights",
    "Patent licence terminates on patent litigation (section 7)",
  ],
  sources: [
    spdx("EPL-2.0"),
    osi("epl-2-0", "Eclipse Public License version 2.0"),
    official("Eclipse Public License 2.0 (official text)", "https://www.eclipse.org/legal/epl-2.0/"),
    SOURCES.eplFaq,
  ],
};

export const CDDL_1_0: LicenseDefinition = {
  ...openSourceBase,
  id: "CDDL-1.0",
  name: "Common Development and Distribution License 1.0",
  spdxId: "CDDL-1.0",
  family: "FILE_LEVEL_COPYLEFT",
  fsfGplCompatible: false,
  sublicensing: "CONDITIONAL",
  patentGrant: true,
  patentRetaliation: true,
  trademarkUse: "PROHIBITED",
  sourceDisclosure: "MODIFIED_FILES",
  copyleft: "FILE_LEVEL",
  networkCopyleft: false,
  sameLicenseRequired: true,
  stateChangesRequired: true,
  description:
    "A file-level copyleft licence derived from MPL-1.1. Covered files and modifications must stay under CDDL and their source must be available when distributed in executable form; Larger Works may combine them with other code.",
  permissions: ["Commercial use", "Modification", "Distribution", "Express patent licence", "Private use"],
  conditions: [
    "Covered files and modifications stay under CDDL-1.0 with source available",
    "Include a copy of the licence and retain notices",
    "Identify yourself as the contributor of modifications",
  ],
  limitations: [
    "No warranty",
    "No liability",
    "No trademark rights",
    "Patent licence terminates on patent litigation (section 6.2)",
  ],
  sources: [
    spdx("CDDL-1.0"),
    osi("cddl-1-0", "Common Development and Distribution License 1.0"),
    SOURCES.fsfLicenseList,
  ],
};
